import Link from 'next/link'
import { ReactNode } from 'react'
import './globals.css'

export const metadata = {
  title: 'CuraFitt',
  description: 'Revolutionizing Recovery: Smarter Physical Therapy for Faster Results',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-900">
        {/* Sticky Nav */}
        <header className="sticky top-0 z-50 bg-white shadow-sm">
          <nav className="max-w-7xl mx-auto flex items-center justify-between p-4">
            <div className="flex items-center space-x-4">
              {/* Logo */}
              <img
                src="/cf_cura.png"
                alt="CuraFitt Logo"
                className="h-10 w-10 object-contain"
              />
              <span className="font-bold text-xl">CuraFitt</span>
            </div>
            <div>
              <ul className="flex space-x-6">
                <li>
                  <Link href="/" className="hover:text-blue-600">
                    HOME
                  </Link>
                </li>
                <li>
                  <Link href="/about" className="hover:text-blue-600">
                    ABOUT US
                  </Link>
                </li>
                <li>
                  <Link href="/team" className="hover:text-blue-600">
                    TEAM
                  </Link>
                </li>
                <li>
                  <Link href="/contact" className="hover:text-blue-600">
                    CONTACT US
                  </Link>
                </li>
                <li>
                  <Link href="/careers" className="hover:text-blue-600">
                    CAREERS
                  </Link>
                </li>
                <li>
                  <Link href="/product" className="hover:text-blue-600">
                    OUR PRODUCT
                  </Link>
                </li>
              </ul>
            </div>
          </nav>
        </header>

        <main className="max-w-7xl mx-auto p-4">{children}</main>

        {/* Footer */}
        <footer className="bg-gray-100 mt-8 p-4 text-center text-sm text-gray-700">
          <p>© {new Date().getFullYear()} CuraFitt. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
